repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        name: Check YAML files
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-case-conflict
        name: Check for case conflicts
      - id: trailing-whitespace
        name: Trim trailing whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        name: Fix end of files
      - id: mixed-line-ending
        name: Fix mixed line endings
        args: ['--fix=lf']
      - id: check-added-large-files
        name: Check for large files
        args: ['--maxkb=10240']
      - id: detect-private-key
        name: Detect private keys
      - id: check-ast
        name: Check Python AST
      - id: check-json
        name: Check JSON files
      - id: check-toml
        name: Check TOML files

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        name: autoflake (Python)
        args: 
          - --in-place
          - --remove-all-unused-imports
          - --remove-unused-variables
          - --expand-star-imports
        files: '\.py$'

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (Python)
        args: ["--profile", "black", "--filter-files"]
        files: '\.py$'

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        name: black (Python)
        args: ['--line-length=88', --target-version=py38]
        files: '\.py$'

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: flake8 (Python)
        args: 
          - --max-line-length=88
          - --extend-ignore=E203,W503
          - --per-file-ignores=__init__.py:F401
        files: '\.py$'

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        name: mypy (Python)
        args: 
          - --ignore-missing-imports
          - --disallow-untyped-defs
          - --no-warn-no-return
          - --warn-redundant-casts
          - --warn-unused-ignores
        files: '\.py$'
        exclude: '^(tests|docs|examples)/'

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        name: codespell
        args: 
          - --skip=*.json,*.csv,*.parquet,*.ipynb
          - --ignore-words-list=ans,ba,datas,fo,hist,iff,ot,rouge,te,ue
        exclude: '^(assets|datasets|pretrained_models)/'

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        name: markdownlint
        args: ['--fix']
        files: '\.md$'

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        name: pyupgrade
        args: [--py38-plus]
        files: '\.py$'